htcstore/urls.py
from django import urls
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('projet.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projet/urls.py
from django.urls import path
from . import views
from .views import *

urlpatterns = [
    path('login/', views.login_page, name='login'),
    path('login-admin/', AdminLogin.as_view(), name="loginadmin"),
    path('logout/', views.logout_page, name='logout'),
    path('enregistrer/', views.enregistrer, name='enregistrer'),
    path('', views.accueil, name='accueil'),
    path('ajouter_art/', views.ajouter_art, name='ajouter_art'),
    path('ordi/<str:pk>/', views.detail_pc, name='ordi'),
    path('like/', views.like, name='like'),
]

projet/models.py
from django.db import models
from django.db.models.base import Model
from django.db.models.deletion import CASCADE, SET_NULL
from django.db.models.fields import BooleanField, CharField, DateTimeField, TextField
from django.contrib.auth.models import User


class Admin(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=100)
    image = models.ImageField(blank=True, null=True)
    mobile = models.CharField(max_length=50)
    
    def __str__(self):
        return self.user.username


class Categorie(models.Model):
    nom = models.CharField(max_length=100)
    
    def __str__(self):
        return self.nom
    

class Ordinateur(models.Model):
    marque = models.CharField(max_length=20)
    nom = models.CharField(max_length=200)
    prix = models.FloatField(null=True)
    categorie = models.ForeignKey(Categorie, on_delete=models.SET_NULL, null=True)
    description = TextField(null=True, blank=True)
    photo = models.ImageField(null=True, blank=True)
    date_creation = models.DateTimeField(auto_now_add=True)
    likesO = models.ManyToManyField(User, default=None, blank=True, related_name='likesO')
    createur = models.ForeignKey(User, on_delete=CASCADE, null=True, related_name='createur')
    maj = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ['-maj', '-date_creation']
    def __str__(self):
        return self.nom
    
    def likestotal(self):
        return self.likesO.count()
    
    @property
    def photoURL(self):
        try:
            url = self.photo.url
        except:
            url = ''
        return url
    
    @property
    def likenum(self):
        return self.likesO.all().count()


class Imagesordi(models.Model):
    ordinateur = models.ForeignKey(Ordinateur, on_delete=models.CASCADE)
    photo = models.ImageField(null=True, blank=True)
    
    def __str__(self):
        return self.ordinateur.nom
    
    


class Message(models.Model):
    utilisateur = models.ForeignKey(User, on_delete=models.CASCADE, related_name='utilisateur')
    ordi = models.ForeignKey(Ordinateur, on_delete=models.CASCADE)
    corps = models.TextField()
    maj = models.DateTimeField(auto_now=True)
    creation = models.DateTimeField(auto_now_add=True)
    likesM = models.ManyToManyField(User, default=None, blank=True, related_name='likesM')
    
    class Meta:
        ordering = ['-maj', '-creation']
    def __str__(self):
        return self.corps
    
    
CHOIX = (
    ('Like', 'Like'),
    ('Unlike', 'Unlike'),
)
class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Ordinateur, on_delete=models.CASCADE)
    valeur = models.CharField(choices=CHOIX, default='like', max_length=10)
    
    def __str__(self):
        return self.post
    

projet/forms.py
from django.contrib.auth import forms
from django.db.models import fields
from django.db.models.base import Model
from django.forms import ModelForm
from django import forms
from .models import Ordinateur
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class OrdiForm(ModelForm):
    class Meta:
        model = Ordinateur
        fields = '__all__'
        exclude = ['createur', 'likesO']
        

class CreerUtilisateur(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        

class AdminLoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput())
    password = forms.CharField(widget=forms.PasswordInput())

projet/views.py
from django.contrib import auth
from django.contrib.auth.models import User
from django.contrib.messages.api import success
from django.views.generic import CreateView, FormView
from django.http import HttpRequest, HttpResponseNotFound, request
from django.urls import reverse, reverse_lazy
from django.http.response import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from .models import Like, Ordinateur, Categorie, Message, Admin
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models import Q
from django.contrib.auth.forms import UserCreationForm
from .forms import OrdiForm, CreerUtilisateur, AdminLoginForm


def login_page(request):
    page = 'login'
    if request.user.is_authenticated:
        return redirect('accueil')
    if request.method =='POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        try:
            user = User.objects.get(username=username)
        except:
            messages.error(request, 'Utilisateur non existant')      
        user = authenticate(request, username=username, password=password)
        
        if user is not None:
            login(request, user)
            if request.user.is_superuser:
                messages.success(request, 'bienvenue Administrateur !')
            else:
                messages.success(request, 'login avec success !')
            return redirect('/')
        else:
            messages.error(request, 'Utilisateur ou mot de passe incorrect !')
    
    
    context = {'page':page}
    return render(request, 'projet/connexion.html', context)


def logout_page(request):
    logout(request)
    return redirect('accueil')


def enregistrer(request):
    form = CreerUtilisateur(request.POST)
    if form.is_valid():
        user = form.save(commit=False)
        user.username = user.username.lower()
        user.save()
        login(request, user)
        messages.success(request, 'enregistrement reussi Bienvenue!')
        return redirect('/')
    else:
        messages.error(request, "erreur lors de l'enregistrement !")
    context = {'form':form}
    return render(request, 'projet/connexion.html', context)


def accueil(request):
    q = request.GET.get('q') if request.GET.get('q') != None else '' 
    ordinateur = Ordinateur.objects.filter(
        Q(categorie__nom__icontains=q) |
        Q(nom__icontains=q) |
        Q(prix__icontains=q)  |
        Q(description__icontains=q)|
        Q(marque__icontains=q)
    )
    categories = Categorie.objects.all()
    context = {'ordinateur':ordinateur, 'categories':categories}
    return render(request, 'projet/accueil.html', context)


@login_required(login_url='login')
def suppri_mess(request, pk):
    message = Message.objects.get(id=pk)
    if request.user != message.user:
        return HttpResponse("vous n'etes pas autorise")
    if request.method=='POST':
        message.delete()
        return redirect('accueil')
    context = {'obj':message}
    return render(request, 'projet/supprimer.html', context)


def detail_pc(request, pk):
    ordi = Ordinateur.objects.get(id=pk)
    user = request.user
    message_ordi = ordi.message_set.all().order_by('-creation')
    if request.method == 'POST':
        message = Message.objects.create(
            utilisateur = request.user,
            ordi=ordi,
            corps=request.POST.get('corps')
        )
        return redirect('ordi', pk=ordi.id)
    
    
    
    # liketotal = likestotal
    context = {'ordi':ordi, 'message':message_ordi, 'user':user}# , 'liketotal': liketotal}
    return render(request, 'projet/detailspc.html', context)


@login_required(login_url='login')
def like(request):
    user = request.user
    if request.method =='POST':
        id_post = request.POST.get('pc_id')
        post_obj = Ordinateur.objects.get(id=id_post)
        
        if user in post_obj.likesO.all():
            post_obj.likesO.remove(user)
        else:
            post_obj.likesO.add(user)
            
        like, creation = Like.objects.get_or_create(user=user, post_id=id_post)
        
        if not creation:
            if like.valeur== 'Like':
                like.valeur ='Unlike'
            else:
                like.valeur= 'Like'
        like.save()
    return render(request, 'projet/detailspc.html')


# admin

class AdminRequiredMixin(object):
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and Admin.objects.filter(user=request.user).exists():
            pass
        else:
            return redirect('/login-admin/')
        return super().dispatch(request, *args, **kwargs)


class AdminLogin(FormView):
    template_name = "loginadmin.html"
    form_class = AdminLoginForm
    success_url = reverse_lazy("projet:ajouter_art")
    
    def form_valid(self, form):
        uname = form.cleaned_data.get("username")
        pword = form.cleaned_data["password"]
        usr = authenticate(username=uname, password=pword)
        context = {"form":self.form_class, "error": "Invalid credentials"}
        if usr is not None and Admin.objects.filter(user=usr).exists():
            login(self, request, usr)
        else:
            return render(self.request, self.template_name, context)
        return super().form_valid(form)
    
    
class CreateView(AdminRequiredMixin, CreateView):
    template_name = "projet/ajouter_art.html"
    form_class = OrdiForm
    success_url = reverse_lazy('/')
  
@login_required(login_url='login')    
def ajouter_art(request):
    if not request.user.is_superuser:
        return HttpResponseNotFound("Vous n'etes pas autorisé ici, seuls les Admin!")
    else:
        form = OrdiForm()
        categories = Categorie.objects.all()
        if request.method=="POST":
            data = request.POST
            form = OrdiForm(request.POST)
            if form.is_valid():
                ordi = form.save(commit=False)
                ordi.createur = request.user
                ordi = Ordinateur.objects.create(
                        marque=data['marque'],
                        nom=data['nom'],
                        prix=data['prix'],
                        categorie=Categorie.objects.get(id=data['categorie']),
                        description=data['description'],
                        photo=request.FILES.get('photo')
                    )
                ordi.save()
                messages.warning(request, "Produit Ajoute avec succes !")
                return redirect('/')
        context = {'form':form, 'categories':categories}
        return render(request, 'projet/ajout_art.html', context)

projet/templates/projet/accueil.html
{% extends 'main.html' %}
{% load static %}

{% block content %}

    <style>
        .home-con{
            display: grid;
            grid-template-columns:1fr 3fr ;
        }
    </style>

<div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;">
<div class="home-con">
  
    <h3>Accueil</h3>

</div>


{% if messages %}
  {% for msg in messages %}
    <div class="alert alert-success alert-dismissible fade show md-2" role="alert" id="msg">
      <strong>Bravo!! </strong>{{msg}}
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"></button>
    </div>
  {% endfor %}

{% endif %}
  



    <div class="row">
        {% for ordi in ordinateur %}
        <div class="col-lg-3">
            <a href="{% url 'ordi' ordi.id %}">
                <img src="{{ordi.photoURL}}" class="thumbnail rounded-top">
            </a>
            
            <div class="box-element produit">
                <h6><strong>{{ordi.nom}}</strong></h6>
                <h6>{{ordi.categorie.nom}}</h6>
                <hr>
                <h6 style="display: inline-block; float: right;">
                    {{ordi.prix|floatformat:2}} FCFA</h6>
                <a class="btn btn-outline-success btn-sm"
                href="{% url 'ordi' ordi.id %}">voir</a>
            </div>
            <br>

        </div>

        {% endfor %}

    </div>

  
{% endblock content %}

  <script>
      setTimeout(
        function(){
          if ($('#msg').length > 0) {
            $('#msg').remove();
          }
      }, 2000)
    </script>
  </div>

projet/templates/projet/ajout_art.html
{% extends 'main.html' %}

{% load crispy_forms_tags %}

{% block content %}

<div class="container">
    <div class="row justify-content-center">
       <div class="col-md-6">
           <div class="">


           </div>
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                <label>Marque</label>
                <input type="text" name="marque" class="form-control">
            </div>

            <div class="form-group">
                <label>Model</label>
                <input type="text" name="nom" class="form-control">
            </div>

            <div class="form-group">
                <label>Prix</label>
                <input type="text" name="prix" class="form-control">
            </div>

            <div class="form-group">
                <label>Categorie</label>
                <select name="categorie" class="form-control">
                    <option value="none">selection categories..</option>
                    {% for categorie in categories %}
                      <option value="{{categorie.id}}">{{categorie.nom}}</option>
                    {% endfor %}
                </select>
            </div>

            <div  class="form-group">
                <label>Description</label>
                <textarea type="text" name="description" class="form-control"></textarea>
            </div>

            <div class="form-group">
                <label>Photos</label>
                <input type="file" name="photo" class="form-control-file">
            </div>
            <button type="submit" class="btn btn-lg btn-primary btn-block">Ajouter</button>
            
        </form>

    </div>
</div>
    
{% endblock content %}
    

projet/templates/projet/connexion.html
{% extends "main.html" %}

{% load crispy_forms_tags %}

{% block content %}

    

{% if page == 'login' %}

    {% for msg in messages %}
        <div class="alert alert-warning alert-dismissible fade show" id="msg" role="alert">
        <strong>Oups !</strong>{{msg}}
        </div>
    {% endfor %}

    <div>
            <div class="row justify-content-center">
                <div class="card" 
                style="width: 28rem; 
                       border: 1px solid #7c7c7c;
                       border-radius: 10px;
                       height: auto;
                       font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;">

                    <div class="card-body">
                        <h4 style="text-align: center;">Login</h4>
                        <div class="card-text">
                            <form action="" method="post">
                                {% csrf_token %}
                                <br>
                                <div class="form-group">
                                    <label>Nom d'utilisateur</label>
                                    <input class="form-control" type="text" name="username" placeholder="Nom d'utilisateur">
                                </div>
                                
                                <div class="form-group">
                                    <label for="">Mot de passe</label>
                                    <input class="form-control" type="password" name="password" placeholder="**********">
                                </div>
                    
                                <input class="btn btn-primary btn-block" type="submit" value="Login">
                            </form>
                            <br>
                            <p>Vous n'avez pas encore de compte ? <a href="{% url 'enregistrer' %}">Creer un compte</a></p>

                        </div>
                    </div>
                </div>
            </div>
            
    </div>

{% else %}

{% for msg in messages %}
<div class="alert alert-danger alert-dismissible fade show" role="alert">
  <strong>Oups!! </strong>{{msg}}
</div>
  
{% endfor %}

    <div class="row justify-content-center">
        <div class="card" 
        style="width: 35rem; 
               border: 1px solid #a2a3a3;
               border-radius: 10px;
               height: auto;">

            <div class="card-body">
                <h4 style="text-align: center;"><strong>Creation de Compte</strong></h4>
                <div class="card-text">
                    <form action="" method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="">Nom d'utilisateur</label>
                            <input class="form-control" type="text" name="username">
                        </div>
                        <div class="form-group">
                            <label for="">Email</label>
                            <input class="form-control" type="text" name="email">
                        </div>
                        <div class="form-group">
                            <label for="">Mot de Passe</label>
                            <input class="form-control" type="password" name="password1">
                        </div>
                        <div class="form-group">
                            <label for="">Confirmation mot de passe</label>
                            <input class="form-control" type="password" name="password2">
                        </div>    
                        <button type="submit" class="btn btn-success btn-block">Enregistrer</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

            
        </div>
    </div>    
{% endif %}

{% endblock content %}

<script>
    setTimeout(
      function(){
        if ($('#msg').length > 0) {
          $('#msg').remove();
        }
    }, 2000)
  </script>

projet/templates/projet/detailspc.html
{% extends 'main.html' %}
{% load static %}

{% block content %}

    <div class="container" style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;">
        <div class="row justify-content-center">
            
            <div class="col-sm-3">
                <h2>Caracteristiques</h2><br>

                <h5>Marque:</h5>
                <p>{{ordi.marque}}</p>

                <h5>Categorie:</h5>
                <p>{{ordi.categorie}}</p>

                <h5>Nom:</h5>
                <p>{{ordi.nom}}</p>

                <h5>Descriprion</h5>
                <p>{{ordi.description}}</p>

                <h6>create on</h6>
                <hp>{{ordi.date_creation}}</hp>
            </div>
            <div class="col-sm-6">
                <a href="{{ordi.photoURL}}">
                    <img src="{{ordi.photoURL}}" class="rounded img-fluid" target="_blank">
                </a>
                <div class="row">
                    {% for io in ordi.imagesordi_set.all %}
                        <div class="col-md-3 p-2 ml-2">
                            <a href="{{io.photo.url}}">
                                <img src="{{io.photo.url}}" class="rounded img-fluid" 
                                style="height: 100px; object-fit: contain;" target="_blank">
                            </a>       
                        </div>                      
                    {% endfor %}

                </div>
            </div>
          </div>        
    </div> 

    <!-- <form action="{% url 'like' %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="pc_id" value="{{ordi.id}}"> 
        {% if user not in ordi.likesO.all %}
            <button class="btn btn-success btn-sm">Like</button>
        {% else %}
        <button class="btn btn-danger btn-sm">Unlike</button>
        {% endif %}        
    </form>
    <strong>{{ ordi.likesO.all.count }} likes</strong> -->


    <br><br>
    <div class="headings d-flex justify-content-between align-items-center mb-3">
        <strong><h3>commentaires</h3></strong>
    </div>
    {% for sms in message %}
            
            <div class="container mt-3">
                <div class="row d-flex justify-content-center">
                    <div class="col-md-6">
                        
                        <div class="card box-elements p-3">
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="user d-flex flex-row align-items-center"> <img src="{% static 'images/test.jpg' %}" width="30" class="user-img rounded-circle mr-2"> <span><small class="font-weight-bold text-primary">{{sms.utilisateur}}</small> <small class="font-weight-bold">{{sms.corps}}</small></span> </div> <small>{{sms.creation|timesince}}</small>
                            </div>
                            <div class="action d-flex justify-content-between mt-2 align-items-center">
                                <div class="reply px-4"> <small>Supprimer</small> <span class="dots"></span> <small>Repondre</small> <span class="dots"></span></div>
                                <div class="icons align-items-center"> <i class="fa fa-star text-warning"></i> <i class="fa fa-check-circle-o check-icon"></i> </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            

    {% endfor %}
    

  {% if request.user.is_authenticated %}

    <div class="container">
        <div class="container">
            <div class="comment-form">
                <form action="" method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="exampleFormControlTextarea1"><h4>Laisser un commentaire</h4></label>
                        <textarea type="text" name="corps" class="form-control" id="exampleFormControlTextarea1" rows="4"></textarea>
                    </div>
                    <input type="submit" class="btn btn-warning" value="Envoyer">
                </form>
            </div>
        </div>

        

    </div>
    
  {% endif %}

{% endblock content %}
    

projet/templates/projet/supprimer.html
{% extends 'main.html' %}


{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <p>Voulez vous vraiment supprimer le message "<strong>{{obj}}</strong>"? 
       Do you really want to delete the message "<strong>{{obj}}</strong>"?</p>
    <a href="{{request.META.HTTP_REFERER}}">Retour</a>

    <input class="btn btn-warning" type="submit" value="OK" />
</form>


{% endblock content %}
    